[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "http://localhost:9763/t/carbon"

[transport]
transport_listener_http_enabled = true
transport_listener_https_enabled = false

[super_admin]
username = "admin"
password = "admin"
