services:
  jenkins:
    network_mode: host
    build: .
    volumes:
      - jenkins_home:/var/jenkins_home

  wso2is:
    network_mode: host
    image: wso2/wso2is:5.11.0
    container_name: wso2is
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true

volumes:
  jenkins_home:
