services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  wso2is:
    image: wso2/wso2is:5.11.0
    container_name: wso2is
    ports:
      - "9443:9443"
      - "9763:9763"
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    volumes:
      - ./deployment.toml:/home/wso2carbon/wso2is-5.11.0/repository/conf/deployment.toml:ro

volumes:
  jenkins_home:
