version: "3.8"

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  wso2is:
    image: wso2/wso2is:5.11.0
    container_name: wso2is
    ports:
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/health"]
      interval: 10s
      retries: 10
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true

  wso2-init:
    image: curlimages/curl:7.85.0
    depends_on:
      wso2is:
        condition: service_healthy
    volumes:
      - ./wso2-init.sh:/wso2-init.sh:ro
    entrypoint: ["/bin/sh", "/wso2-init.sh"]

volumes:
  jenkins_home:
