services:
  zimbra-not-vuln:
    image: zimbra-not-vuln
    container_name: zimbra-not-vuln
    networks:
       - my_network
    dns:
      - 127.0.0.1
      - 8.8.8.8
    hostname: zimbra86-docker.zimbra.io
    environment:
      - PASSWORD=password
      - MailSSLPort=443
      - AdminPort=7071
      - AdminURL=/admin
      - DOCKER_DEFAULT_BRIDGE_DNS=disable
    ports:
      - "8500:8443"
    tty: true
    restart: always

  zimbra-vuln:
    image: zimbra-vuln
    container_name: zimbra-vuln
    networks:
       - my_network
    dns:
      - 127.0.0.1
      - 8.8.8.8
    hostname: zimbra86-docker.zimbra.io
    environment:
      - PASSWORD=password
      - MailSSLPort=443
      - AdminPort=7071
      - AdminURL=/admin
      - DOCKER_DEFAULT_BRIDGE_DNS=disable
    ports:
      - "8443:8443"
    tty: true
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - my_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

networks:
  my_network:
    driver: bridge
