version: '3.3'

services:
  agentscope:
    build:
      context: .  # Path to the directory containing the Dockerfile
    ports:
      - "5000:5000"
    stdin_open: true  # Keeps the stdin open (equivalent to -it for interactive mode)
    restart: unless-stopped
